### ISSUE TITLE
Trampoline Pending Requirements Tracking

### ISSUE THREAD

**Issue by arik-so** [lightningdevkit/rust-lightning#2757]
- [ ] Serialization
  - [ ] Variable-length onion packet
    - [ ] Calculate available remaining length for nesting
  - [x] Outbound (#2756)
    - [x] Allow variable lengths for nested onions?
  - [ ] Inbound deserialization
- [ ] Wire Communication
  - [ ] Feature flag (#2756)
  - [ ] Advertise trampoline support
  - [ ] Flag-aware hop selection for packet construction
- [ ] Interaction
  - [ ] Expose method for sending to Trampoline node
  - [ ] Forwarding payments as Trampoline node
  - [ ] TBD: Potential interaction with blinded paths?
- [ ] Bindings Support

**Comment by moneyball** [comment]
Can this be added to https://github.com/orgs/lightningdevkit/projects/3?

And also de-dup'd with
https://github.com/lightningdevkit/rust-lightning/issues/2299
