### ISSUE TITLE
LSPS1 integration tracking issue

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/rust-lightning#3480]
- [x] Refactor LSPS1 service side
~~- [ ] Add client-side validation of `OrderParameters` vs `LSPS1Options`~~
- [x] Add service-side validation of `OrderParameters` vs `LSPS1Options`
~~- [ ] Extend client-side configuration~~
- [x] Extend service-side configuration
~~- [ ] Extend service-side API (e.g., to signal/forward `channel_ready`)~~
- [x] Add service-side persistence (where needed)
- [x] Add integration tests
